environment:
  GODEL_TEST_ENV_VAR: test-var-content
plugins:
  resolvers:
  - /Users/abradshaw/go/src/github.com/palantir/godel/integration_test/86383546/1654053055/repo/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{OS}}-{{Arch}}-{{Version}}.tgz
  plugins:
  - locator:
      id: com.palantir:test-env-var-integration-1677804245-258756194412691204-plugin:1.0.0
exclude:
  names:
  - \..+
  - vendor
  paths:
  - godel
