amalgomators:
  gonform:
    config: apps/gonform/formatters.yml
    output-dir: apps/gonform/generated_src
    pkg: amalgomatedformatters
  gunit:
    config: apps/gunit/testers.yml
    output-dir: apps/gunit/generated_src
    pkg: amalgomatedtesters
  okgo:
    config: apps/okgo/checks.yml
    output-dir: apps/okgo/generated_src
    pkg: amalgomatedchecks
