plugins:
  resolvers:
    - "https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz"
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.0.0
        checksums:
          darwin-amd64: ba9e79e96ea687152476b17dec91101109937fb9c65b2245006200d4fa068e81
          linux-amd64: f81c6374e3801344271757ee83380c9a3d70a7bebef7f36456af4717abcfa87f
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - "\\..+"
    - "vendor"
    - "testdata"
  paths:
    - "godel"
