tags:
  distgo:
    paths:
      - "apps/distgo"
    exclude:
      names:
        - "dockertests"
  docker-distgo:
    paths:
      - "apps/distgo/cmd/dist/dockertests"
  gonform:
    paths:
      - "apps/gonform"
  gunit:
    paths:
      - "apps/gunit"
  okgo:
    paths:
      - "apps/okgo"
  integration:
    paths:
      - "integration_test"
