tags:
  distgo:
    paths:
      - "apps/distgo"
  docker-distgo:
    paths:
      - "apps/docker/distgo"
  gonform:
    paths:
      - "apps/gonform"
  gunit:
    paths:
      - "apps/gunit"
  okgo:
    paths:
      - "apps/okgo"
  integration:
    paths:
      - "integration_test"
